- hosts: 192.168.0.49
  roles:
  - role: user

    user_name: a1
    user_id: 1111
    user_primary_group: a1
    user_primary_group_id: 1111
    user_password: $6$5dt3/2Jf/KYlEk.$nb50pFrfysK/e4wE/wt0klEEiUZ5VN30ErF.hcAuTf.IMIx712NE3fzfu4Ap3IeW78qRJBqecpMesP8rOOhNO1
    user_authorized_key: .ssh/id_rsa
    user_home_dir: /home/a1
