---
- hosts: all
  become: yes
  gather_facts: False
  pre_tasks:
   - setup:
       filter: ansible_os_family
#  gather_subset:
#    - '!all'
#    - '!any'
  tasks:
  - debug:
      var: ansible_os_family

  - name: Install httpd Debian
    apt: name=apache2 state=latest
    when: ansible_os_family == 'Debian'

  - name: install httpd Centos
    yum: name=httpd state=latest
    when: ansible_os_family == 'RedHat'
