- hosts: localhost
  vars:
    user_name: a1
    user_id:
    user_primary_group: a1
    user_primary_group_id:
    user_password: test
    user_authorized_key:
    user_home_dir: /home/a1

    tasks:
    - name: Create user
      user:
        name: "{{ user_name }}"
