- hosts: localhost
  vars:
    user_name: a1
    user_id: 1111
    user_primary_group: a1
    user_primary_group_id: 1111
    user_password: $6$5dt3/2Jf/KYlEk.$nb50pFrfysK/e4wE/wt0klEEiUZ5VN30ErF.hcAuTf.IMIx712NE3fzfu4Ap3IeW78qRJBqecpMesP8rOOhNO1
    user_authorized_key: .ssh/id_rsa
    user_home_dir: /home/a1

  tasks:
  - name: Create group
    group:
      name: "{{ user_primary_group }}"
      gid: "{{ user_primary_group_id }}"
      state: present

  - name: Create user
    user:
      name: "{{ user_name }}"
      uid: "{{ user_id }}"
      password: "{{ user_password }}"
      group: "{{ user_primary_group_id }}"
      state: present
      createhome: yes
      home: "{{ user_home_dir }}"
  - debug: msg={{ user_name }}

  - name: Create ssh key for user
    user:
      name: "{{ user_name }}"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: "{{ user_authorized_key }}"
